# Generated by Django 4.2.16 on 2024-09-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvantagesElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.CharField(max_length=15, verbose_name='Верхняя надпись')),
                ('middle', models.CharField(max_length=5, verbose_name='Средняя надпись')),
                ('bottom', models.CharField(max_length=15, verbose_name='Нижняя надпись')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Сорт.')),
            ],
            options={
                'verbose_name': 'Пункт преимуществ',
                'verbose_name_plural': 'Пункты преимуществ',
                'ordering': ['my_order'],
            },
        ),
        migrations.CreateModel(
            name='MenuElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название пункта меню')),
                ('url', models.CharField(max_length=100, verbose_name='url')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Сорт.')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ['my_order'],
            },
        ),
    ]
